SRC_TRG_TXT_DIC = {
    # Human face
    'tanned': (['face'],
               ['tanned face']),
    'pale': (['face'],
             ['pale face']),
    'makeup': (['person'],
               ['person with makeup']),
    'no_makeup': (['person'],
                  ['person without makeup']),
    'old': (['person'],
            ['old person']),
    'young': (['person'],
              ['young person']),
    'beards': (['person'],
               ['person with beards']),
    'angry': (['face'],
              ['angry face']),
    'surprised': (['face'],
                  ['surprised face']),
        'sad': (['face'],
                ['sad face']),
        'disgusted': (['face'],
                            ['disgusted face']),
    'smiling': (['face'],
                ['smiling face']),
    'blond_hair': (['person'],
                   ['person with blond hair']),
    'red_hair': (['person'],
                 ['person with red hair']),
    'grey_hair': (['person'],
                  ['person with grey hair']),
    'curly_hair': (['person'],
                   ['person with curly hair']),
    'bald': (['person'],
                   ['person with bald head']),


    'nicolas': (['Person'],
                ['Nicolas Cage']),
    'zuckerberg': (['Person'],
                   ['Mark Zuckerberg']),
    'benedict': (['Person'],
              ['Benedict Cumberbatch']),
    'gogh': (['photo'],
             ['painting by Gogh']),
    'frida': (['photo'],
              ['self-portrait by Frida Kahlo']),
    'modigliani': (['photo'],
                   ['Painting in Modigliani style']),
    'sketch': (['photo'],
              ['sketch']),
    'watercolor': (['photo'],
                   ['Watercolor Art with Thick Brushstrokes']),
    'elf': (['Human'],
            ['Tolkien elf']),
    'super_saiyan': (['Human'],
                     ['Super saiyan']),
    'pixar': (['Human'],
              ['3D render in the style of Pixar']),
    'neanderthal': (['Human'],
                    ['Neanderthal']),
    'zombie': (['Human'],
               ['Zombie']),
    'jocker': (['Human'],
               ['The Jocker']),

# Additional Human
        'man': (['a person'],
                ['a man']),
        'woman': (['a person'],
                ['a woman']),
        'long_hair': (['person'],
                   ['person with long hair']),
        'short_hair': (['person'],
                   ['person with long hair']),
        

#     Dog face
    'dog_nicolas': (['Dog'],
                    ['Nicolas Cage']),
    'dog_yorkshire': (['Dog'],
                      ['Yorkshire Terrier']),
    'dog_smiling': (['Dog'],
                    ['Smiling Dog']),
    'dog_zombie': (['Dog'],
                   ['Zombie']),
        'dog_zombie_dog':(['Dog'],
                        ['Zombie Dog']),
        'dog_super_saiyan_dog':(['Dog'],
                                ['Super saiyan dog']),
        'dog_starry_night':(['Dog'],
                        ['A painting of a dog in the style of The Starry night']),
        'dog_pixar':(['Dog'],
                        ['Dog in the style of Pixar 3D animation']),
        'dog_cubism':(['Dog'],
                        ['A painting of a Dog in the style of Cubism']),
        'dog_puppy':(['Dog'],
                        ['Puppy']),
        'dog_fat':(['Dog'],
                        ['Fat Dog']),



    'dog_super_saiyan': (['Dog'],
                         ['Super saiyan']),
    'dog_venom': (['Dog'],
                  ['Venom']),
    'dog_bear': (['Dog'],
                 ['Bear']),
    'dog_fox': (['Dog'],
                ['Fox']),
    'dog_wolf': (['Dog'],
                 ['Wolf']),
    'dog_hamster': (['Dog'],
                    ['Hamster']),

        'dog_tongue': (['Dog'],
                ['Dog Tongue']),
        'dog_happy': (['Dog'],
                ['Happy Dog']),
        'dog_sad': (['Dog'],
                ['Sad Dog']),
        'dog_sleepy': (['Dog'],
        ["Sleepy Dog"]),
        'dog_angry':(['Dog'],
        ['Angry Dog']),
        'dog_sunglasses':(['Dog'],
        ['Dog Sunglasses']
        ),
        'dog_fat':(['Dog'],
        ['Fat Dog']),
        'dog_baby':(['Dog'],
                ['Baby Dog']),
        'dog_golden_retriever':(['Dog'],
                ['golden retriever']),
'dog_cat':(['Dog'],['Dog having fur of Cat']),
'dog_cat2':(['Dog'],['Cat with shape of Dog']),
'dog_cat3':(['Dog'],['Cat']),

# Church
    'church_snow': (['Church'],
                    ['snowy day']),
    'church_night': (['Church'],
                     ['at night']),
    'church_red_brick': (['Church'],
                         ['Red brick wall Church']),
    'church_golden': (['Church'],
                      ['Golden Church']),
    'church_wooden_house': (['Church'],
                            ['Wooden House']),
    'church_gothic': (['Church'],
                      ['Gothic Church']),
    'church_ancient_tower': (['Church'],
                             ['Ancient traditional Asian tower']),
    'church_temple': (['Church'],
                      ['Temple']),
    'church_factory': (['church'],
                       ['factory with chimneys']),
    'church_department_store': (['church'],
                                ['department store']),
        'church_wooden_church':(['Church'],
                        ['Wooden Church']),
        'church_snowy_church': (['Church'],
                                ['snowy church']),

    # Bedroom
    'bedroom_blue': (['Bedroom'],
                     ['Blue tone Bedroom']),
    'bedroom_green': (['Bedroom'],
                      ['Green tone Bedroom']),
    'bedroom_golden': (['Bedroom'],
                       ['Golden Bedroom']),
    'bedroom_princess': (['Bedroom'],
                         ['Princess Bedroom']),
    'bedroom_palace': (['Bedroom'],
                       ['Palace Bedroom']),
    'bedroom_wooden': (['Bedroom'],
                       ['Wooden Bedroom']),
    'bedroom_window': (['Bedroom'],
                        ['Bedroom with window']),
    'bedroom_miniature': (['Bedroom'],
                        ['Bedroom miniature']),
    'bedroom_hotel': (['Bedroom'],
                        ['Hotel Bedroom']),
        'bedroom_hospital': (['Bedroom'],
                        ['Hospital ward']),
        'bedroom_karaoke': (['Bedroom'],
                        ['karaoke room']),

# MetFACES
        'metface_smiling': (['painting of a person'],
                                ['painting of a Smiling person']),
        'metface_angry': (['painting of a person'],
        ['painting of a Angry person']),
        'metface_surprised': (['painting of a person'],
        ['painting of a Surprised person']),
        'metface_sad': (['painting of a person'],
        ['painting of a Sad person']),
        'metface_disgusted': (['painting of a person'],
        ['painting of a Disgusted person']),


# For test
        'test': (['image'], ['image']),

# ImageNet
        'orange2tennis': (['An Orange'], ['Tennis ball']),
        'orange2apple': (['a photo of an orange'], ['a photo of an apple']),
        'acoustic_guitar2electric_guitar': (['a photo of an acoustic guitar'], ['a photo of an electric guitar']),
        'coral_fungus2mushroom': (['a photo of a coral fungus'], ['a photo of a mushroom']),
        'tailed_frog2green_frog': (['a photo of a tailed frog'], ['a photo of a green frog']),
        'Persian_cat2Persian_cat_closed_eyes': (['a photo of a Persian cat'], ['a photo of a Persian cat with closed eyes']),
        'orange2hamster': (['a photo of an orange'], ['a photo of a hamster']),
        'orange2basketball': (['a photo of an orange'], ['a photo of a basketball']),
        'orange2paprika': (['a photo of an orange'], ['a photo of a paprika']),
        'orange2lemon': (['a photo of an orange'], ['a photo of a lemon']),
        'orange2strawberry': (['a photo of an orange'], ['a photo of a strawberry']),
        'orange2pineapple': (['a photo of an orange'], ['a photo of a pineapple']),
        'orange2ping_pong_ball': (['a photo of an orange'], ['a photo of a ping pong ball']),
        'orange2mushroom': (['a photo of an orange'], ['a photo of a mushroom']),

}